INSERT INTO libros (id_libro, titulo, autor, lanzamiento, cantidad, create_at) VALUES ('bk01', 'Python para principiantes', 'Antonio Perez', 2020, 10, '2020-09-01');
INSERT INTO libros (id_libro, titulo, autor, lanzamiento, cantidad, create_at) VALUES ('bk02', 'El código Da Vinci', 'Dan Brown', 2003, 8, '2004-03-01');
INSERT INTO libros (id_libro, titulo, autor, lanzamiento, cantidad, create_at) VALUES ('bk03', 'La carretera', 'Cormac McCarthy', 2006, 2, '2006-10-01');
INSERT INTO libros (id_libro, titulo, autor, lanzamiento, cantidad, create_at) VALUES ('bk04', 'Los hombres me explican cosas', 'Rebecca Solnit', 2014, 3, '2015-08-11');
INSERT INTO libros (id_libro, titulo, autor, lanzamiento, cantidad, create_at) VALUES ('bk05', 'Cien años de soledad', 'Gabriel García Márquez', 1967, 6, '2000-12-01');
INSERT INTO libros (id_libro, titulo, autor, lanzamiento, cantidad, create_at) VALUES ('bk06', 'Crimen y castigo', 'Fiodor Dostoievski', 1866, 4, '2002-11-10');
INSERT INTO libros (id_libro, titulo, autor, lanzamiento, cantidad, create_at) VALUES ('bk07', '1984', 'George Orwell', 1949, 7, '2002-09-08');
INSERT INTO libros (id_libro, titulo, autor, lanzamiento, cantidad, create_at) VALUES ('bk08', 'Don Quijote de la Mancha', 'Miguel de Cervantes', 1605, 1, '2000-03-01');
INSERT INTO libros (id_libro, titulo, autor, lanzamiento, cantidad, create_at) VALUES ('bk09', 'Harry Potter y la piedra filosofal', 'J.K. Rowling', 1997, 9, '2000-04-01');
INSERT INTO libros (id_libro, titulo, autor, lanzamiento, cantidad, create_at) VALUES ('bk10', 'El Señor de los Anillos', 'J.R.R. Tolkien', 1954, 11, '2000-11-01');
INSERT INTO usuarios (id_usuario, nombre, apellido, fecha_registro, prestamo) VALUES ('US01', 'Pedro', 'Sánchez', '2020-02-23', 'si');
INSERT INTO usuarios (id_usuario, nombre, apellido, fecha_registro, prestamo) VALUES ('US02', 'Ana', 'García', '2018-03-12', 'no');
INSERT INTO usuarios (id_usuario, nombre, apellido, fecha_registro, prestamo) VALUES ('US03', 'Juan', 'López', '2019-05-19', 'si');
INSERT INTO usuarios (id_usuario, nombre, apellido, fecha_registro, prestamo) VALUES ('US04', 'María', 'Martínez', '2021-06-15', 'no');
INSERT INTO usuarios (id_usuario, nombre, apellido, fecha_registro, prestamo) VALUES ('US05', 'Luis', 'Fernández', '2017-02-07', 'si');
INSERT INTO usuarios (id_usuario, nombre, apellido, fecha_registro, prestamo) VALUES ('US06', 'Laura', 'Ramírez', '2020-05-24', 'no');
INSERT INTO usuarios (id_usuario, nombre, apellido, fecha_registro, prestamo) VALUES ('US07', 'Carlos', 'Gómez', '2018-05-19', 'si');
INSERT INTO usuarios (id_usuario, nombre, apellido, fecha_registro, prestamo) VALUES ('US08', 'Sofía', 'Hernández', '2019-07-02', 'no');
INSERT INTO usuarios (id_usuario, nombre, apellido, fecha_registro, prestamo) VALUES ('US09', 'Pablo', 'Díaz', '2022-06-01', 'si');
INSERT INTO usuarios (id_usuario, nombre, apellido, fecha_registro, prestamo) VALUES ('US10', 'Elena', 'Pérez', '2016-10-09', 'no');
